---
- name: Gather Host Information and Save to YAML
  hosts: localhost  # Replace with the hostname or IP address of the target host
  gather_facts: yes

  tasks:
    - name: Save gathered information to a local variable
      set_fact:
        host_info:
          hostname: "{{ ansible_hostname }}"
          vcpus: "{{ ansible_processor_vcpus }}"
          memory: "{{ ansible_memtotal_mb }}"
          disk_size: "{{ ansible_mounts[0].size_total / (1024 ** 3) | int }}"

    - name: Save gathered information to a YAML file
      copy:
        content: "{{ host_info | to_nice_yaml(indent=2) }}"
        dest: /host_data/info00.yaml
