---
- hosts: localhost
  name: Edit VM IP Notes
  gather_facts: False
  
  vars:
    - pxmx_cluster: "Proxmox LX"
    - api_host: "172.18.33.129"
    - vms_list: []

  vars_files:
    - "/etc/ansible/vault/vault.yml"

  tasks:
   - name: Create API Session
     uri:
        url: https://{{ api_host }}/api2/json/access/ticket
        method: POST 
        validate_certs: no 
        body_format: form-urlencoded
        body:
          username: "{{ pve_user }}"
          password: "{{ pve_pass }}" 
     register: session 

   - name: Get All Nodes
     uri: 
        url: https://{{ api_host }}/api2/json/nodes
        method: GET
        validate_certs: no
        headers:
          Cookie: "PVEAuthCookie={{ session.json.data.ticket }}"
     register: api_nodes 

   - include_tasks: ../tasks/proxmox_map_vms.yml
     with_sequence: start=0 end="{{ api_nodes.json.data | length - 1}}"
     loop_control:
         loop_var: node_idx

   - include_tasks: ../tasks/proxmox_get_ips.yml
     with_items: "{{ vms_list }}"
     loop_control:
          loop_var: vm_list

